### ISSUE TITLE
Path errors on Windows?

### ISSUE THREAD

**Issue by Rush** [webdiscus/pug-loader#12]
![image](https://user-images.githubusercontent.com/115926/154133694-933d979f-06dd-44a5-ad0e-c8150e6499bc.png)

**Comment by webdiscus** [comment]
Hello @Rush,

yes, I know this issue. It is a Node+Windows problem.
What system are you using general: macOS, Linux or Windows?

The problem is that in Windows is the path like `D:/Projects/nexus/portal/server/views/fonts-preload.pug` will be as relative recognised, although that is absolute path.

I will to experiment on Windows with paths, so find the solution, maybe simple adding of `/` at start will be enough, so like `/D:/Projects/`.

**Comment by Rush** [comment]
My friend is using Windows.

**Comment by Rush** [comment]
Thank you. No need to backport. I'll wait for #11

**Comment by webdiscus** [comment]
The new version `1.7.3` contains both fixes for #11 and #12
