### ISSUE TITLE
Missing peer dependency pug-walk

### ISSUE THREAD

**Issue by m10** [webdiscus/pug-loader#19]
The loader uses the `pug-walk` module [1] but there is no corresponding entry in the package.json.

`pug-walk` should be added to the peerDependencies.

Also I noticed `webpack-merge` being a dependency. Probably this should just be a dev dependency?

[1] https://github.com/webdiscus/pug-loader/blob/18f7e19059bbdb928a24b3bd49fab1c3f6189fdf/src/index.js#L7

**Comment by m10** [comment]
1.
You are right that it is a dependency of dependencies of `pug`. Still IMO it should be a peer dependency since you use that module directly and not just `pug`, the dependencies of pug could _theoretically_ change...

2. 
Well, I should have checked how it's used :P

(originally i filed this issue because of webpack complaining about missing `pug-walk` module, but there must have been something wrong with my node_modules)

**Comment by webdiscus** [comment]
An npm warning like `...missing pug-walk module ...` is displayed if old Pug <= 2.x.x is used.
Sometimes the `package-lock.json` contains not actual info about all packages, then helps the deleting `package-lock.json` with `node_modules` and new install.

Since Pug 3, all `pug-` dependencies have been included to monolithic Pug. I have research this question and I know 100% that all `pug-` packages like `pug-walk` and others are the parts of Pug self.
If this changes in future versions of Pug, I will fix it.
I see no reason to use something that is not required at the moment. ;-)
